### ISSUE TITLE
Rating is always starting from default starting value when swiping the stars

### ISSUE THREAD

**Issue by aik117** [Monte9/react-native-ratings#118]
Thanks for the library.

I observed when swiping the stars, the rating is always starting from default starting value e.g if the ratingCount is 5 and when i swipe the stars, the stars start to fill from ratingCount/2 (i.e 2.5) although i have updated the starting value to the updated value. Is this the default behaviour? Can you please make the stars swipe from where the finger is put. Here is my code

    <Rating 
        showRating
        imageSize = { 50 }
        ratingCount = { 5 }
        fractions = { 1 }
        startingValue = { rating }
        onFinishRating = {(ratingValue) => ratingCompleted(ratingValue, "qualityofservicerating")}
    />

![Simulator Screen Shot - iPhone 8 - 2020-09-18 at 12 46 43](https://user-images.githubusercontent.com/17512745/93571920-8ccb9780-f9ae-11ea-9c0e-400d2a839a4a.png)

**Comment by SolovyovIlya** [comment]
Agreed, this looks really awkward and makes swiping more difficult.

**Comment by sshivananda** [comment]
Fixed in #135
