### ISSUE TITLE
Set value on Rating

### ISSUE THREAD

**Issue by LucasMonteiro1** [Monte9/react-native-ratings#12]
How to set a value after rendering the component other than by startingValue?

**Comment by LucasMonteiro1** [comment]
I used setCurrentRating to set the value, but it would be nice to have a "value" property.

**Comment by Monte9** [comment]
Yes, for now, `setCurrentRating` is the best way to accomplish this. Feel free to submit a PR if you think there is a better way to do this.

**Comment by chai86** [comment]
@LucasMonteiro1 I was also interested in having the rating set to a value of my choosing each time the component rendered. I use SwipeRating.js. Right now if I use "startingValue" it only does it for the 1st time, then every other rating it doesn't set to a value I want. How did you achieve this? Could you please share how you did this?
