### ISSUE TITLE
Is there any CHANGELOG?

### ISSUE THREAD

**Issue by MatheusRich** [Monte9/react-native-ratings#120]
I couldn't find any CHANGELOG.md or History.md for this repository. Is there any information about upgrades and breaking changes?

**Comment by sshivananda** [comment]
there isn't one for earlier changes - but changes post v7.5.0 are documented in https://github.com/Monte9/react-native-ratings/releases .
Is that useful?

**Comment by MatheusRich** [comment]
@sshivananda sorry for the late response! I think that will do! So, any breaking changes will be reported in releases, right?

**Comment by sshivananda** [comment]
Yep -they will be
