### ISSUE TITLE
airbnbrating not shown probably

### ISSUE THREAD

**Issue by nazacity** [Monte9/react-native-ratings#125]
<AirbnbRating
                onFinishRating={(val) => setRating(val)}
                showRating={false}
                size={25}
                count={5}
                defaultRating={3}
              />

please see the video below
https://drive.google.com/file/d/1zVZiLysdCidMltshlXudOYsFO5i5Hbup/view?usp=sharing

i am facing that rating star not shown probably
when i deselect the rating star has gone

please help

**Comment by soundaraj** [comment]
i am also have this problem

**Comment by dfalcon-rua** [comment]
Hello, there is solution to that? I'm still have it.

**Comment by vinaygoyal20** [comment]
I was able to resolve this by making change in library,
react-native-ratings/src/components/Star.js
Line no 51
from
tintColor: fill && selectedColor ? selectedColor : undefined,

to
tintColor: fill && selectedColor ? selectedColor :"#e5e5e5",

**Comment by vinaygoyal20** [comment]
I was able to resolve this by making change in library,
react-native-ratings/src/components/Star.js
`
Line no 51
from
tintColor: fill && selectedColor ? selectedColor : undefined,

to
tintColor: fill && selectedColor ? selectedColor :"#e5e5e5"`

**Comment by vinaygoyal20** [comment]
I was able to resolve it by making Changes in file
react-native-ratings/src/components/Star.js
From
> tintColor: fill && selectedColor ? selectedColor : undefined,

**Comment by sshivananda** [comment]
Fixed in v7.4.0
