### ISSUE TITLE
Android Stars Are Not Displaying Correctly 

### ISSUE THREAD

**Issue by oporter1** [Monte9/react-native-ratings#126]
I am working with `"react-native-elements"` {Rating} on iOs and android. It works great on iOs but on android the star images are coming in as a solid block. See below picture. Any idea why this would be happening? Is it happening to anyone else?

```
import {Rating} from "react-native-elements";
import CustomCallout from "./customCallout";
```

```
                        <CustomCallout>
                          <Text style={{fontFamily: Font.Bold}}>
                            {marker.placeName}
                          </Text>
                          <Rating
                            imageSize={15}
                            readonly
                            startingValue={marker.rating}
                            style={{marginLeft: -35}}
                          />
                          <Text style={{fontFamily: Font.Regular}}>
                            {marker.placeType}
                          </Text>
                        </CustomCallout>
```
```
class CustomCallout extends React.Component {
  render() {
    return (
      <View style={[styles.container, this.props.style]}>
        <View style={styles.bubble}>
          <View style={styles.amount}>{this.props.children}</View>
        </View>
        <View style={styles.arrowBorder} />
        <View style={styles.arrow} />
      </View>
    );
  }
}
```

![image](https://user-images.githubusercontent.com/12777243/95469165-4f26b280-094d-11eb-9fd0-ad72f7e61ab3.png)

**Comment by GurjantSinghAffle** [comment]
I am using the same  "react-native-elements" library.it's working fine for ios but in android, stars disappear on selecting, please have look.

> ![IMG_20201021_161828](https://user-images.githubusercontent.com/61281021/96710366-984d1c80-13b9-11eb-9a04-74331460f76d.jpg)
      <AirbnbRating
            defaultRating={defaultRating}
            type='custom'
            ratingImage={Assets.userType.ratingbg}
            ratingColor='#FFCB27'
            ratingBackgroundColor='#c8c7c8'
            count={count}
            showRating={false}
            imageSize={30}
            starStyle={{ height: 30, width: 32 }}
            onFinishRating={onratingCompleted}
        />
am also try with custom type to set a watermark image.

**Comment by Rooib** [comment]
same here

**Comment by GurjantSinghAffle** [comment]
> same here

Hi Rooib, you can use the new Library.
Link: https://www.npmjs.com/package/react-native-rating
maybe it helpful for you

**Comment by vinaygoyal20** [comment]
I was able to resolve it by making Changes in file
react-native-ratings/src/components/Star.js
From
tintColor: fill && selectedColor ? selectedColor : undefined,
to
tintColor: fill && selectedColor ? selectedColor :"#e5e5e5",

**Comment by OlMrGreen** [comment]
> I was able to resolve it by making Changes in file
> react-native-ratings/src/components/Star.js
> From
> tintColor: fill && selectedColor ? selectedColor : undefined,
> to
> tintColor: fill && selectedColor ? selectedColor :"#e5e5e5",

Thanks, helped me instantly!

**Comment by jeffreybenabou** [comment]
i have the same problem, can it be fixed perement?

**Comment by shubhamkes** [comment]
I am too having the same issue, Isnt it fixed yet in new latest versions?

**Comment by sshivananda** [comment]
This has been fixed. Please try with the latest version.

**Comment by parmarravi** [comment]
I am also having this issue.It's not working!!

**Comment by Devoagency** [comment]
Having the same issue with the latest version

**Comment by thenderson55** [comment]
Same issue on iOS

**Comment by syedamirali14** [comment]
just remove `halfStarEnabled={true}` and it will not break in android
