### ISSUE TITLE
Unable to change input type of rating

### ISSUE THREAD

**Issue by jbyomuhangi** [Monte9/react-native-ratings#128]
Hi, is there any way of changing the input type of the rating? I see in the docs it says it supports both swipe and tap rating, but it doesn't show a way to chose which one to use. I am using the component as shown in the docs but seems to default to swipe rating. How might I change it to use tap rating?

**Comment by sshivananda** [comment]
@jbyomuhangi did you see the demo app included in the repo?

**Comment by sshivananda** [comment]
For AirbnbRating use: 
```javascript
<AirbnbRating showRating={true} />
```
