### ISSUE TITLE
Don't set color for normal star

### ISSUE THREAD

**Issue by PiPyL** [Monte9/react-native-ratings#131]
I select 5 stars. After that I select 3 stars. Then 4 star and 5 star failed background color. It is white color -> failed. I can't set color for normal star when use AirbnbRating? Who can help me? Thanks

**Comment by nguyenductoan1995** [comment]
> I select 5 stars. After that I select 3 stars. Then 4 star and 5 star failed background color. It is white color -> failed. I can't set color for normal star when use AirbnbRating? Who can help me? Thanks

change tintColor from undefine to color

**Comment by sshivananda** [comment]
@PiPyL can you try with 7.4.0
