### ISSUE TITLE
Does not work with snack.expo.io

### ISSUE THREAD

**Issue by malivp3494** [Monte9/react-native-ratings#14]
you have lodash, lodash.times in devDependencies,
![dsqrzrdueaalqcw](https://user-images.githubusercontent.com/15379131/34450897-297eabb6-ed3d-11e7-83f8-50f19675e19e.jpg)
 so the expo snack is not going to install it.

**Comment by Monte9** [comment]
Hey @malivp3494! Sorry about that. 

I will publish a fix for it this weekend. Stay tuned.

**Comment by Monte9** [comment]
Ok, I have published `v5.3.0`. That should fix the issue. You can try & verify it with an expo app. 

But I tried it on Snack and it still reverts back to `v4.3.0`. I think we will just have to wait until snack updates to the latest version of this library. I'll leave this issue open until that is resolved.

**Comment by Monte9** [comment]
Hey @malivp3494 & @alpcoskun! It's working with expo now. Thanks for being patient.

Here is the snack demo for you to try: https://snack.expo.io/HyVZcDxBz
