### ISSUE TITLE
Latest changes broke the rating code

### ISSUE THREAD

**Issue by KalAvroniev** [Monte9/react-native-ratings#140]
Issue is in src/SwipeRating.js, line 177
`( startingValue + value ) / imageSize;`
Should be:
` startingValue + value / imageSize;`

Also, startingValue property does not work because when calling `this.setCurrentRating( this.props.startingValue );` in `componentDidMount` the `this.state.isComponentMounted` is not yet set to true

Same file as above, line 105
You should change the `componentDidMount` to `componentDidMount() {
    try {
      this.setState( { display: true, isComponentMounted: true }, () => this.setCurrentRating( this.props.startingValue ) );
    } catch ( err ) {
      // eslint-disable-next-line no-console
      console.log( err )
    }
  }`

**Comment by sshivananda** [comment]
@KalAvroniev thanks for creating this issue - and the awesome writeup. This is being fixed in #141
