### ISSUE TITLE
Convert the existing codebase to Typescript and Change the components to use React Hooks

### ISSUE THREAD

**Issue by khushal87** [Monte9/react-native-ratings#143]
The package currently uses JavaScript and Class based components approach. With the changing needs its better to adapt to TypeScript as well as use React Hooks architecture. Therefore I want to convert the codebase to the same mentioned above. Can I proceed @Monte9 @sshivananda ? Thank you.

**Comment by sshivananda** [comment]
Hey @khushal87  - typescript and adding tests to this repo are on the top of my list right now. Any help on either is highly appreciated.

**Comment by khushal87** [comment]
Okay I am working on the above two issues as mentioned and then I will work on writing tests for the repo. Thanks for your reply @sshivananda

**Comment by sshivananda** [comment]
I can take up the tests if you are already on the typescript migration

**Comment by khushal87** [comment]
Yes I am on the typescript migration @sshivananda

**Comment by khushal87** [comment]
@sshivananda  Any guesses about the type of `fractionsType` in SwipeRatings.tsx?

**Comment by sshivananda** [comment]
Fixed in #144
