### ISSUE TITLE
Default Rating 0 doesn't work

### ISSUE THREAD

**Issue by khushal87** [Monte9/react-native-ratings#148]
As a user, I want when my component loads any of the stars are not filled by default. Or if we have an option to do so.

**Comment by daniloitj** [comment]
Same problem

**Comment by daniloitj** [comment]
In TapRAting.js line 100 chage: if (defaultRating) to if (defaultRating!=null)  (https://github.com/Monte9/react-native-ratings/blob/master/src/TapRating.tsx)

**Comment by khushal87** [comment]
I have already fixed it @daniloitj You will see this fixed soon with an update
