### ISSUE TITLE
Please update React dependency

### ISSUE THREAD

**Issue by lyquocnam** [Monte9/react-native-ratings#16]
i see an error when build:
`npm ERR! peer dep missing: react@react@16.0.0-alpha.12, required by react-native-ratings@4.1.0`
this maybe from package react dependency, please help !

**Comment by Monte9** [comment]
Hey @yairopro! Sorry about that. 

I will publish a fix for it this weekend. Stay tuned.

**Comment by Monte9** [comment]
Updated to use `react: "16.0.0"`. Please update to `v5.3.0`
