### ISSUE TITLE
 Unable to resolve module lodash.times

### ISSUE THREAD

**Issue by yairopro** [Monte9/react-native-ratings#17]
When compiling, I get this error :
`error: bundling failed: UnableToResolveError: Unable to resolve module "lodash.times" from ".\node_modules\react-native-ratings\src\rating.js":  Module does not exist in the module map`

**Comment by Monte9** [comment]
Hey! Sorry about that. 

I will publish a fix for it this weekend. Stay tuned.

**Comment by yairopro** [comment]
Thanks 👍

**Comment by Monte9** [comment]
Ok, I have published `v5.3.0`. That should fix the issue. You can try & verify it with an expo app.

**Comment by yairopro** [comment]
Thanks.
But I don't use expo. Would it still be fixed?

**Comment by Monte9** [comment]
Yes, it should be fixed.

**Comment by yairopro** [comment]
I confirm! 👍
