### ISSUE TITLE
AirbnbRating how to change the color that comes by default in the stars

### ISSUE THREAD

**Issue by marcossk8** [Monte9/react-native-ratings#18]
Hi, I'm using AirbnbRating, can you change the color of the stars?

**Comment by Monte9** [comment]
You can! Please refer to this issue: https://github.com/react-native-training/react-native-elements/issues/863#issuecomment-361889506

**Comment by marcossk8** [comment]
@Monte9  I had already read, the problem is that I want to do it with an Icon, can I perform ratingImage with an Icon?

**Comment by Monte9** [comment]
@marcossk8 for now, you cannot directly use an icon from `@expo/vector-icons` or `react-native-vector-icons`.

Although if it's just 1 or two icons.. you could download it as images and then pass in custom images to the rating's component like so:

```
const WATER_IMAGE = require('./water.png')

<Rating
  type='custom'
  ratingImage={WATER_IMAGE}
  ratingColor='#3498db'
  ratingBackgroundColor='#c8c7c8'
  ratingCount={10}
  imageSize={30}
  onFinishRating={this.ratingCompleted}
  style={{ paddingVertical: 10 }}
/>
```

**Comment by pkbiswal321** [comment]
React-native-elemenet try following selectedColor props.

<AirbnbRating
         selectedColor="#000000"
          count={5}
          defaultRating={0}
          size={24}
          showRating={false}
          onFinishRating={ratingCompleted}
     />

**Comment by AsmaTidafi** [comment]
selectedColor and unselectedColor
