### ISSUE TITLE
Airbnb Rating

### ISSUE THREAD

**Issue by Marcin-Falkowski** [Monte9/react-native-ratings#185]
Hi, Airbnb Raing not have a one of the props from the docs. This prop is a unSelectedColor
![image](https://user-images.githubusercontent.com/88496638/236451954-02b9a2ce-4cdc-4355-832f-f00f11610466.png)

**Comment by dbacinski** [comment]
seems like this is a fix https://github.com/Monte9/react-native-ratings/pull/182/files

**Comment by Monte9** [comment]
The PR has been merged and will be released in the next version!
