### ISSUE TITLE
Please provide option to enable/disable rating. For in some cases, we just want to display the overall average rating.

### ISSUE THREAD

**Issue by tan116** [Monte9/react-native-ratings#20]
It would also be great if you can provide a way for the UI to show decimal rating values.

For example, if the average rating is 4.2, the fifth star should get filled to show the 0.2 value. It looks much cleaner and richer that way. Hope you upload the fix soon. Can't wait to use this amazing lib.

**Comment by waheed25** [comment]
yes i need that enable and disable props badly i just use this module for ratings but after that i got requirement for disable and enable but i didn't find this in docs if any way to do this please share it.

**Comment by fahadakhan96** [comment]
@tan116 @waheed25 Use the ```readonly``` prop.

**Comment by fahadakhan96** [comment]
As a workaround, you may use the ```Rating``` component from ```react-native-elements```. It is inspired from this package, ```react-native-ratings```. In the ```react-native-elements``` version, there is a ```readonly``` prop that disables the rating component.

**Comment by waheed25** [comment]
Yeah ```readonly``` works perfect.

**Comment by rohitbhirud** [comment]
just use a View as parent to  Rating component & set pointerEvents to none
```
<View pointerEvents="none">
     <Rating />
</View>
```

**Comment by Monte9** [comment]
There is a `readonly` prop that you can use to disable input. Also you can use `isDisabled` prop as well. Look at the `/example` folder to see how to use it.

**Comment by amanrathore18** [comment]
> There is a `readonly` prop that you can use to disable input. Also you can use `isDisabled` prop as well. Look at the `/example` folder to see how to use it.

As i check example doesn't exist and passing boolean in `isDisabled` doesn't work for me. For solution i've used

```
<View pointerEvents="none">
     <Rating />
</View>
```
