### ISSUE TITLE
Star Icon Color Doesn't change

### ISSUE THREAD

**Issue by Bilal112** [Monte9/react-native-ratings#31]
![image](https://user-images.githubusercontent.com/23139110/47017042-a6348b00-d16a-11e8-958d-6a2bc1699899.png)

**Comment by Bilal112** [comment]
![image](https://user-images.githubusercontent.com/23139110/47017110-d714c000-d16a-11e8-991a-8d967acbf3b0.png)

**Comment by joelrorseth** [comment]
Per the ratingColor docs, you need to set type='custom' for this to work: 

> Pass in a custom fill-color for the rating icon; use this along with type='custom' prop above (optional)

**Comment by SafdarSikander** [comment]
it changes only filled star color, how to change unfilled star color.

**Comment by Bilal112** [comment]
ok
