### ISSUE TITLE
Missing readonly attribute for AirbnbRating

### ISSUE THREAD

**Issue by zenorocha** [Monte9/react-native-ratings#38]

**Comment by diegogalocha** [comment]
First of all, excelente library.

I have the same issue as my mate zenorocha.

**Comment by ialmoqren** [comment]
Not sure, but try passing `isDisabled={true}`
I think it will work as I found in the source code it's being used to disable the Stars' buttons.

**Comment by Rana-Muhammad-Amir** [comment]
Use   
readonly={true} 
for readonly....
this is available in the props...

**Comment by ialmoqren** [comment]
@Rana-Muhammad-Amir readonly is available in the Rating component props but not the AirbnbRating component where isDisabled should be used instead

**Comment by Monte9** [comment]
@zenorocha as suggested above, for `AirbnbRating` component, you can use the `isDisabled` prop to achieve this same effect. #41 should fix it.

**Comment by zenorocha** [comment]
Thanks!
