### ISSUE TITLE
rating on tap is not working and also i want to disable swipe for rating

### ISSUE THREAD

**Issue by logindharam** [Monte9/react-native-ratings#44]
rating on tap is not working and also i want to disable swipe for rating

thanks in advance 
look forward to hear from you soon

**Comment by michaelVictoriaDev** [comment]
Any update on this ?

**Comment by neerajemorphis** [comment]
I am looking for tap functionality with it.

**Comment by Akash-T2S** [comment]
Any update on this?

**Comment by KishanGujarati** [comment]
did anyone try <AirbnbRating />?
<Rating /> does'nt have rating on tap but <AirbnbRating /> have so you can try <AirbnbRating />.
it works in my case.

`<AirbnbRating
  count={10}
  defaultRating={5}
  size={20}
/>`

try this

**Comment by Monte9** [comment]
Yes, `AirbnbRating` is meant to be on-tap. Please use that if that's your use case.

**Comment by Anujmoglix** [comment]
AirbnbRating star is not visible in my Android MOTO E phone .

**Comment by omorhefere** [comment]
Just spent some time struggling with tapping when using the <Rating /> component I didn't  realise that it wasn't for tapping. 

Maybe we could rename them to <SwipeableRating /> and <TappableRating />?

**Comment by KishanGujarati** [comment]
@omorhefere 
did you try `<AirbnbRating />` ?
