### ISSUE TITLE
Why didn't add selectedColor to README ducument?

### ISSUE THREAD

**Issue by wvalen** [Monte9/react-native-ratings#45]
I just to find a way to change the selectedColor of AirbnbRating.  But  was sad to search no result in readme and issues. 

Fortunately，i find selectedColor in  react-native-ratings/src/components/Star.js，and it could work out  my demand.

`<AirbnbRating
    count={5}
    selectedColor={Config.colors.c1}
    showRating={false}
    defaultRating={starsData[item.id] || 5}
    size={24}
    onFinishRating={ratingCompleted}
    >`

**Comment by Monte9** [comment]
maybe I missed it. Would appreciate it if you can submit a PR for it so that others can find it easily.

**Comment by wvalen** [comment]
It's my pleasure, but i have no access rights to push code.
I think the follow description should be ok.

### AirbnbRating

| prop | default | type | description |
| ---- | ---- | ----| ---- |
| defaultRating | 3 | number | Initial value for the rating |
| reviews | ['Terrible', 'Bad', 'Okay', 'Good', 'Great'] | string[] | Labels to show when each value is tapped e.g. If the first star is tapped, then value in index 0 will be used as the label |
| count | 5 | number | Total number of ratings to display |
| selectedColor | #f1c40f | string (color) | Pass in a custom fill-color for the rating icon |
| showRating | `true` | boolean | Determines if to show the reviews above the rating |
| isDisabled | false | boolean | Whether the rating can be modiefied by the user |
| onFinishRating | none | function(value: number) | Callback method when the user finishes rating. Gives you the final rating value as a whole number |

**Comment by Monte9** [comment]
Updated: https://github.com/Monte9/react-native-ratings#airbnbrating

Thanks @wvalen! 💯 

Also if you would like to contribute & improve this library, I'd be happy to give you access to this repo.
