### ISSUE TITLE
Space between Stars should be configurable

### ISSUE THREAD

**Issue by KangYoosam** [Monte9/react-native-ratings#53]
## What
When I use AirbnbRating(TapRating), space between each start can not be configured.

Here is where it defines spaces. (`margin: 3`).
https://github.com/Monte9/react-native-ratings/blob/763464f0d53abb3b37f414a9d29d8a277138b649/src/components/Star.js#L63-L67

I want to give `starStyle` prop to this component.

**Comment by ramaguduri** [comment]
+1 can this be merged?

**Comment by IntelliJAbhishek** [comment]
this is the only issue stoping me to use this library

**Comment by luvnish19** [comment]
Why this thing is not fixed till now?

**Comment by matias3981** [comment]
Honestly would be a really nice feature, i was very happy when i found out this lib, but now i have to dismiss to use it because. i need to set the space between the stars

**Comment by sshivananda** [comment]
Fixed in v6.4.0
