### ISSUE TITLE
How to get the real time rating value?

### ISSUE THREAD

**Issue by chai86** [Monte9/react-native-ratings#56]
@Monte9 I'm currently using the 'showRating' property, however i'd like to display the value (e.g **4.7** out of 10) in a different font, and maybe use a `<Text>` from react native to display it. How can i get the running real time value of this figure (whilst swipe rating) to render in `<Text>` ? Can you make this available as a property?

**Comment by pureinx** [comment]
@chai86 if you are using `AirbnbRating` you can get an actual rating value inside `onFinishRating` callback as a first argument.
