### ISSUE TITLE
Issue with border color

### ISSUE THREAD

**Issue by halbano** [Monte9/react-native-ratings#58]
Hey there, I am experiencing an issue with the border color of the stars component. 

![Screen Shot 2019-08-22 at 3 48 51 PM](https://user-images.githubusercontent.com/5341623/63541503-9dcc7f80-c4f4-11e9-9a66-ad01beb93886.png)

I shouldn't have this yellow border coming from the asset. The idea is to have the green color as the border for the filled and unfilled state. 

My actual setup is: 

```
<Rating
          ratingColor={Palette.Accent}
          ratingBackgroundColor={Palette.Accent}
          ratingCount={6}
          startingValue={rating.count}
          onFinishRating={rating.onRatingChanged}
          minValue={1}
          readonly={readonly}
          imageSize={20}
          fractions={0}
          type="custom"
        />
```

What can I do? Cannot set the tintColor because of the transparent parts of the asset. The only alternative to fix this is with a custom image? 

Thank you in advance for your time.

**Comment by nachozullo** [comment]
Im having the same problem

**Comment by mattrace** [comment]
Any updates on this? Thanks!

**Comment by BGdroid** [comment]
????

**Comment by Kastamarov** [comment]
> ????

https://github.com/Monte9/react-native-ratings/issues/26#issuecomment-480532803

**Comment by mahmoudafer** [comment]
> > ????
> 
> this works for me.
> just set tintColor='#fff'
> 
> [#26 (comment)](https://github.com/Monte9/react-native-ratings/issues/26#issuecomment-480532803)

this issue should be closed thanks to this answer

**Comment by nachozullo** [comment]
Thanks @Kastamarov

**Comment by ecemac** [comment]
> > ????
> 
> this works for me. just set tintColor='#fff'
> 
> [#26 (comment)](https://github.com/Monte9/react-native-ratings/issues/26#issuecomment-480532803)

This doesn't work for me on iOS 15. I'm still getting the yellow border on stars.

**Comment by Jonathan0wh** [comment]
This should be in doc or example in README
