### ISSUE TITLE
Rating: 'componentWillReceiveProps is deprecated'

### ISSUE THREAD

**Issue by pessoft** [Monte9/react-native-ratings#63]
### Reproduction
Add basic <Rating> element.

### Expected behavior
Fully comply with 0.60 RN.

### Warning
Warning: componentWillReceiveProps is deprecated and will be removed in the the next major version. Use static getDerivedStateFromProps instead. Please update the following components: SwipeRating.

**Comment by Monte9** [comment]
This is fixed in v6.5
