### ISSUE TITLE
AirbnbRating not rendering properly

### ISSUE THREAD

**Issue by winardis** [Monte9/react-native-ratings#68]
Hi i tried your package and on my case it doesn't render properly on the first time
i need to navigate to a different screen then go back to the screen with AirbnbRating after that then it will render properly

here is the recording of the issue i mentioned
[https://drive.google.com/file/d/1Lgb2n_PI63oitst6ga9V2lIqH3zoaRs1/view?usp=sharing](url)

here is how i use the rating with hardcoded value
  ```
 <AirbnbRating
      showRating={false}
      count={5}
      defaultRating={5}
      size={20} />
```

**Comment by henoktsegaye** [comment]
having the same issue here

**Comment by henoktsegaye** [comment]
@winardis  I suggest using this package https://github.com/djchie/react-native-star-rating or building one for your self, this package looks like nobody is maintaining it

**Comment by Monte9** [comment]
Checkout the updated demo app in this repo. It has working examples for all ratings.
