### ISSUE TITLE
How to proportionally fill the stars

### ISSUE THREAD

**Issue by mrinal-tech-prescient** [Monte9/react-native-ratings#83]
How can we fill the star for a rating say 1.2; so it should be 1 star completely filled and the second star filled 0.2 portion. How to get this?

**Comment by nachozullo** [comment]
I need the same feature. It's possible?

**Comment by nachozullo** [comment]
@Monte9 could be possible to add this feature in the TapRating component? I realized that SwipeRating works with decimal/float ratings could it be extended to TapRating? 

PD: Thanks for this library!!

**Comment by sshivananda** [comment]
Fixed in #135
