### ISSUE TITLE
propTypes is deprecated

### ISSUE THREAD

**Issue by littlehome-eugene** [Monte9/react-native-ratings#85]
I'm hitting `SwipeRating.js:324 Uncaught TypeError: Cannot read property 'source' of undefined
    at Module../node_modules/react-native-ratings/src/SwipeRating.js (SwipeRating.js:324)`

and the issue is discussed here..

https://github.com/necolas/react-native-web/issues/1543

**Comment by Monte9** [comment]
This has been fixed in this PR: https://github.com/Monte9/react-native-ratings/pull/92/files
