### ISSUE TITLE
Get Rating from AirbnbRating

### ISSUE THREAD

**Issue by rubensbarreto** [Monte9/react-native-ratings#9]
Hi!
First of all I'd like to thank you for the implementation of AirbnbRating, really good!
I'm having some problems trying to access the rating after the user clicks on it.
The onFinishRating method described on the API doesn't seem to work with AirbnbRating, how can I access the rating?
I tried declaring starSelectedInPosition to a function of mine, I'm then able to get the rating, bit the fill stops working and the stars won't get colored.

Regards,

**Comment by Monte9** [comment]
Hey! Thanks for using this library.

I have been a bit busy with work lately. I can look into it this weekend and get back to you.

**Comment by catrieldapice** [comment]
+1

**Comment by Monte9** [comment]
@rubensbarreto @catrieldapice I have added the `onFinishRating` callback method to AirbnbRating as well. You can see the changes here: https://github.com/Monte9/react-native-ratings/commit/f64469da53ae58a2db25fa0031f5d6b5e30c1002

I have published a new version `v4.0` with these changes. Let me know if you still have any trouble using it.

I have also updated the example app to use this callback method. You can see how to use it here: https://github.com/Monte9/react-native-ratings/blob/master/example/App.js#L29 
Hope this helps.

**Comment by rubensbarreto** [comment]
Awesome, but when trying to set state, it will render undefined:

  ratingCompleted(rating) {
    console.log('Rating is: ' + rating);
    this.setState({
        rating: rating
      });
  }
![img_0885](https://user-images.githubusercontent.com/9420303/30725196-39464b20-9f19-11e7-9f03-4153391de015.PNG)

**Comment by Monte9** [comment]
can you console.log `rating`. I feel like you might be doing something else that's weird there, cause its complaining about this.setState in the error message.

**Comment by rubensbarreto** [comment]
Yes, console.log rating works normally.
I just tried it again using the example source code on the repository , just change the code on App.js to:

  ratingCompleted(rating) {
    console.log('Rating is: ' + rating);
    this.setState({
      rating: rating
    });
  }

You'll see the same issue.

`import React, { Component } from 'react';
import { StyleSheet, Text, View, Platform, ScrollView } from 'react-native';

import Rating from './src/rating'
import AirbnbRating from './src/AirbnbRating'

const WATER_IMAGE = require('./assets/water.png');

export default class App extends Component {
  ratingCompleted(rating) {
    console.log('Rating is: ' + rating);
    this.setState({
      rating: rating
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <View style={styles.headingContainer}>
          <Text style={styles.titleText}>React Native Ratings</Text>
          <Text style={styles.subtitleText}>gestures for the win!</Text>
        </View>
        <ScrollView style={styles.viewContainer}>
          <Text style={[styles.titleText, { marginTop: 30, color: '#e74c3c', fontSize: 22 }]}>Airbnb-style Tap Ratings</Text>
          <AirbnbRating />
          <AirbnbRating
            count={11}
            reviews={["Terrible", "Bad", "Meh", "OK", "Good", "Hmm...", "Very Good", "Wow", "Amazing", "Unbelievable", "Jesus"]}
            defaultRating={11}
            size={20}
            onFinishRating={this.ratingCompleted}
          />
          <Text style={[styles.titleText, { marginTop: 30, color: '#9b59b6', fontSize: 22 }]}>Whatsapp-style Swipe Ratings</Text>
          <View style={{justifyContent: 'center', alignItems: 'center', marginBottom: 30}}>
            <Rating
              showRating
              imageSize={40}
              onFinishRating={this.ratingCompleted}
              style={{ paddingVertical: 10 }}
            />
            <Rating
              showRating
              type="star"
              fractions={1}
              startingValue={3.6}
              readonly
              imageSize={40}
              onFinishRating={this.ratingCompleted}
              style={{ paddingVertical: 10 }}
            />
            <Rating
              type="custom"
              ratingImage={WATER_IMAGE}
              ratingColor="#3498db"
              ratingBackgroundColor="#ceee"
              ratingCount={10}
              imageSize={30}
              onFinishRating={this.ratingCompleted}
              showRating
              style={{ paddingVertical: 10 }}
            />
            <Rating
              type="heart"
              ratingCount={3}
              fractions={2}
              startingValue={1.57}
              imageSize={40}
              onFinishRating={this.ratingCompleted}
              showRating
              style={{ paddingVertical: 10 }}
            />
          </View>
        </ScrollView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  headingContainer: {
    paddingTop: 50,
  },
  titleText: {
    fontSize: 25,
    fontWeight: 'bold',
    textAlign: 'center',
    paddingVertical: 5,
    fontFamily: Platform.OS === 'ios' ? 'Menlo-Bold' : null,
    color: '#27ae60',
  },
  subtitleText: {
    fontSize: 18,
    fontWeight: '400',
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'Trebuchet MS' : null,
    color: '#34495e',
  },
  viewContainer: {
    flex: 1
  },
});
`

**Comment by rubensbarreto** [comment]
Hi Monte9, any update on this issue?

**Comment by KishanGujarati** [comment]
you have to use different name for the variable like

`this.setState({
ratingBar: rating
});`

and

`ratingCompleted = (rating) => {
  this.setState({ratingFinal:rating});
Alert.alert("Your Rating is: " + ratingBar);}`

then you can use 'ratingBar' for displya rating

**Comment by fernandomunizz89** [comment]
I'm getting the same error.
I tried everything and I did not succeed.
Please I need help!

`    ratingCompleted = (rating) => {
        this.setState({ lawyerRating: rating });
        //return rating;
    } `

`<View style={{ marginVertical: 0, height: 110, paddingTop: 20 }}>
                            <AirbnbRating
                                count={5}
                                reviews={['Péssimo', 'Ruim', 'Normal', 'Bom', 'Excelente']}
                                defaultRating={0}
                                size={40}
                                onFinishRating={this.ratingCompleted}
                            />
                        </View>`

**Comment by KishanGujarati** [comment]
hi @fernandomunizz89 
sorry for late reply

you can try this

`ratingCompleted = (rating) => { 
       this.setState({ 
             lawyerRating: {value : rating }
        }); //return rating; 
}`

**Comment by pureinx** [comment]
Hey @fernandomunizz89! Looks now it works with useState hook:
`const [ratingCount, setRatingCount] = useState(0);`
`onFinishRating={rating => setRatingCount(rating)}`

**Comment by aikhan** [comment]
`onFinishRating={rating => this.setState({ratingGiven:rating})}

`

For those who are still stuck

**Comment by Monte9** [comment]
Thanks @aikhan @pureinx & @KishanGujarati.

Closing this issue now.

**Comment by swatiappzlogic** [comment]
how can I show fractional ratings in this
