### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by juanjsebgarcia** [Monte9/react-native-ratings#94]
We've just had a major semver version bump (which I assume means a breaking change), but there's no changelog or release notes anywhere?

Appreciate the work on the repo!

**Comment by Monte9** [comment]
Yeah, I dropped the ball on that. Sorry! This repo isn't very active, so you could look at the commits and see the changes. Mostly just removed the old `ViewPropTypes` in favor of `PropTypes`

https://github.com/Monte9/react-native-ratings/pull/92/files
