### ISSUE TITLE
StartingValue not working

### ISSUE THREAD

**Issue by Relax594** [Monte9/react-native-ratings#99]
When setting startingValue the value gets ignored on first render due to the component not finished mounting. Because of this the setState does not get called and so the initialValue stays default.

```
'#### rating', 0.2
'#### ratingCount', 1
'#### value', -213.33333333333331
'#### isComponentMounted', false
```

Setting the value on the second render is fine then.

```
'#### rating', 0.30000000000000004
'#### ratingCount', 1
'#### value', -142.22222222222217
'#### isComponentMounted', true
```

So the first render the value is ratingCount / 2 (default) and the second render is 0.2.

Minimal code:
```
const [progress, setProgress] = useState(0.1);

<Button onPress={() => setProgress(progress * 2)} />
<Rating
      readonly={true}
      ratingCount={1}
      fractions={1}
      startingValue={progress}
 />
```

Inside componentDidMount you set the state to "isComponentMounted: true". But at the time you call this.setCurrentRating() the state is still false. Due to this the initial position does not get set.
Issue is here:
```
async componentDidMount() {
        try {
            this.setState({ display: true, isComponentMounted: true });
        } catch (err) {
            console.log(err);
        }

        console.log('#### didMount', this.state.isComponentMounted);
        this.setCurrentRating(this.props.startingValue);
    }
```

**Comment by sshivananda** [comment]
Fixed in v7.6.1
